// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlbdeneyuyueziuvxlzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsYmRlbmV5dXl1ZXppdXZ4bHpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MTgzMTAsImV4cCI6MjA3MDM5NDMxMH0.jVxXfIO41o75kV-_awn0dx-nuqJMYIm5tqjQdpqF7pA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});